#!/bin/bash

echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║                                                                      ║"
echo "║          🚀 PUSH PARA GITHUB - AMIGO OCULTO MÁGICO 🚀               ║"
echo "║                                                                      ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 Informações do Repositório:"
echo "   - Conta: devjuniorcoelho@gmail.com"
echo "   - Repositório: amigo-oculto-magico"
echo "   - Branch: main"
echo ""
echo "═══════════════════════════════════════════════════════════════════════"
echo ""
echo "🔐 AUTENTICAÇÃO NECESSÁRIA"
echo ""
echo "Você precisa de um Personal Access Token do GitHub."
echo ""
echo "Se você JÁ TEM um token:"
echo "  1. Digite seu username: devjuniorcoelho"
echo "  2. Cole seu token como senha"
echo ""
echo "Se você NÃO TEM um token:"
echo "  1. Pressione Ctrl+C para cancelar"
echo "  2. Acesse: https://github.com/settings/tokens"
echo "  3. Clique em 'Generate new token (classic)'"
echo "  4. Nome: 'Amigo Oculto Deploy'"
echo "  5. Marque: ☑️ repo (Full control)"
echo "  6. Clique em 'Generate token'"
echo "  7. COPIE O TOKEN"
echo "  8. Execute este script novamente"
echo ""
echo "═══════════════════════════════════════════════════════════════════════"
echo ""
echo "Pressione ENTER para continuar ou Ctrl+C para cancelar..."
read

echo ""
echo "🚀 Fazendo push para GitHub..."
echo ""

git push -u origin main

if [ $? -eq 0 ]; then
    echo ""
    echo "═══════════════════════════════════════════════════════════════════════"
    echo ""
    echo "✅ SUCESSO! Código enviado para o GitHub!"
    echo ""
    echo "🔗 Seu repositório: https://github.com/devjuniorcoelho/amigo-oculto-magico"
    echo ""
    echo "🎯 PRÓXIMOS PASSOS:"
    echo ""
    echo "1️⃣ Acesse: https://vercel.com"
    echo "2️⃣ Clique em 'Add New...' → 'Project'"
    echo "3️⃣ Selecione: devjuniorcoelho/amigo-oculto-magico"
    echo "4️⃣ Configure as variáveis de ambiente:"
    echo "   - VITE_APP_ID=app-7vco8tnvi77l"
    echo "   - VITE_SUPABASE_URL=https://ynkfknbenccgrnkvzmoo.supabase.co"
    echo "   - VITE_SUPABASE_ANON_KEY=[copie do arquivo .env]"
    echo "5️⃣ Clique em 'Deploy'"
    echo "6️⃣ Aguarde 2-5 minutos"
    echo "7️⃣ ✅ Pronto! Seu app estará no ar!"
    echo ""
    echo "═══════════════════════════════════════════════════════════════════════"
    echo ""
else
    echo ""
    echo "═══════════════════════════════════════════════════════════════════════"
    echo ""
    echo "❌ ERRO ao fazer push!"
    echo ""
    echo "Possíveis causas:"
    echo "  - Token inválido ou expirado"
    echo "  - Token sem permissão 'repo'"
    echo "  - Repositório não existe"
    echo "  - Sem conexão com internet"
    echo ""
    echo "Soluções:"
    echo "  1. Gere um novo token em: https://github.com/settings/tokens"
    echo "  2. Certifique-se de marcar 'repo' (Full control)"
    echo "  3. Verifique se o repositório existe"
    echo "  4. Tente novamente"
    echo ""
    echo "═══════════════════════════════════════════════════════════════════════"
    echo ""
fi
